#!/usr/bin/lua

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 6/3/24 4:23 PM
---

local tf = require "tf_module"

local ubus_set_cmd_1 = "ubus call uci set '{\"config\":\"system\",\"section\":\"tfortis\", \"type\":\"system\", \"values\":{\""
local ubus_set_cmd_2 = "\":\""
local ubus_set_cmd_3 = "\"}}'"

local function set_description()
    if (arg[1] ~= nil and arg[2] ~= nil) then
        local set_cmd = ubus_set_cmd_1 .. arg[1] .. ubus_set_cmd_2 .. arg[2] .. ubus_set_cmd_3
        tf.executeCommand(set_cmd)
    else
        print("error: description - command failed")
    end
end

set_description()
