#!/bin/sh /etc/rc.common

START=97
STOP=01
USE_PROCD=1
PROG=/usr/bin/tf_device_monitor

append_string() {
	local section="$1"
	local option="$2"
	local value="$3"
	local _val
	config_get _val "$section" "$option"
	[ -n "$_val" ] && append args "$3 $_val"
}

#with executable
start_instance() {
  echo "start_instance"
  local section="$1"
  echo "section = ${section}"
  local enabled

  config_get_bool enabled "${section}" 'enabled' 0

  if [ $enabled -gt 0 ]; then
    echo "find tfdm disabled"
    return 1
  fi

  args=""
  append_string "$section" 'interface' '-i'

  procd_open_instance

  echo "procd_open_instance ${args}"
  procd_set_param command $PROG $args
  # Send stdout/stderr output to the system log
  # Use command logread to see the log
  procd_set_param stderr 0
  procd_set_param stdout 0
  procd_close_instance
}

stop_instance() {
  local cfg="$1"
}

reload_service()
{
  echo "Explicitly restarting service, are you sure you need this?"
  stop
  start
}

start_service() {
  echo "Start service"
  config_load 'tf_device_monitor'
  config_foreach start_instance 'tf_device_monitor'
}

# This is not neccessary here,
# but we include it for the sake of the example
stop_service() {
  echo "Stop service"
  config_load 'tf_device_monitor'
  config_foreach stop_instance 'tf_device_monitor'
}


