#!/usr/bin/lua

---
--- Generated by Luanalysis
--- Created by sheverdin.
--- DateTime: 2/26/24 10:55 AM
---

local tf = require "tf_module"

local sysDevParam = {
    if_name = "if_name",
    dev_name = "dev_name"
}

local function main_getNetDeviceInfo()
    local cmd_getDeviceInfo = tf.ubusList.cmd_ubus ..  tf.ubusList.cmd_get ..  tf.ubusList.cmd_prefix .. tf.ubusList.cmd_config ..
            "tf_device_monitor" .. tf.ubusList.cmd_section .. "sysDevName" .. tf.ubusList.cmd_suffix

    local jsonData = tf.collectJsonTable(cmd_getDeviceInfo)
    if jsonData ~= nil then
        if type(jsonData.values) == "table" then
            for k,value in pairs(jsonData.values[arg[1]]) do
                print(value)
            end
        else
            print("")
        end
    end
end

main_getNetDeviceInfo()





