#!/usr/bin/lua

---
--- Generated by Luanalysis
--- Created by sheverdin.
--- DateTime: 2/28/24 3:07 PM
---

local tf = require "tf_module"

local count = 0

local function find_interFace(netInfo)
    local foundStatus = "not_found"
    for section_name, section in pairs(netInfo) do
        if section[".type"] == "interface" then
            if section_name ~= "loopback" then
                if section["device"] ~= nil then
                else
                    print("")
                end
                if section["device"] == arg[1] then
                    foundStatus = "found"
                    print(foundStatus)
                    print(section["device"])
                    print(section_name)
                    for _, dev in pairs(netInfo) do
                        if dev[".type"] == "device" then
                            if dev[".name"] ~= nil then
                                if dev["name"] == section["device"] then
                                    if dev["macaddr"] ~= nil then
                                        print(dev["macaddr"])
                                    else
                                        print("00:00:00:00:00:00")
                                    end
                                end
                            end
                        end
                    end

                    if section["ipaddr"] ~= nil then
                        print(section["ipaddr"])
                    else
                        print("0.0.0.0")
                    end

                    if section["netmask"] ~= nil then
                        print(section["netmask"])
                    else
                        print("0.0.0.0")
                    end

                    if section["gateway"] ~= nil then
                        print(section["gateway"])
                    else
                        print("255.255.255.255")
                    end
                end
            end
        end
    end
    if foundStatus == "not_found" then
        print("not_found")
    end
end

local function main_getNetInfo()
    if arg[1] == nil or arg[1] == "" then
        print("error: device name must be presented")
        return 1
    end
    local cmd_getNetInfo = "ubus call uci get '{\"config\":\"network\"}'"
    local netInfo = tf.collectJsonTable(cmd_getNetInfo)
    if netInfo ~= nil then
        netInfo = netInfo["values"]
        find_interFace(netInfo)
    else
        print("error: network config can not readable")
        return 1
    end
end

main_getNetInfo()
