#!/usr/bin/lua

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 8/9/24 1:14 PM
---


package.path = "/etc/tf_clish/scripts/rsyslog/?.lua;" .. package.path

local tf      = require "tf_module"
local log = require "log_module"

local filter_listConfig = {}
local action_listConfig = {}
local rule_listConfig   = {}

local function run_log_show()
    if arg[1] == "all" then
        log.getFilter_list(filter_listConfig)
        log.getAction_list(action_listConfig)
        log.getRules_list(rule_listConfig)
        log.print_filterListConfig("all", filter_listConfig)
        log.print_actionListConfig("all", action_listConfig)
        log.print_ruleListConfig("all", rule_listConfig)
    elseif arg[1] == "filter" then
        log.getFilter_list(filter_listConfig)
        log.print_filterListConfig("all", filter_listConfig)
    elseif arg[1] == "action" then
        log.getAction_list(action_listConfig)
        log.print_actionListConfig("all", action_listConfig)
    elseif arg[1] == "rule" then
        log.getRules_list(rule_listConfig)
        log.print_ruleListConfig("all", rule_listConfig)
    else
        print("error: log unknown parameter")
    end
end

run_log_show()
