#!/usr/bin/lua

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 9/8/24 15:50 PM
---
local tf = require "tf_module"

local cmd_get_syslog_config = "ubus call uci get '{\"config\":\"syslog\"}'"

local log_paramList = {
    "state",
    "proto",
    "port",
}

local log_configList = {
    { name = "enabled",   str = "\tstate:       " },
    { name = "log_port",  str = "\tport:        " },
    { name = "log_proto", str = "\tprotocol:    " }
}

local function run_config_log()
    print("Syslog config:")
    local log_jsonConfigInfo = tf.collectJsonTable(cmd_get_syslog_config)
    log_jsonConfigInfo = log_jsonConfigInfo.values
    for _, dict in pairs(log_jsonConfigInfo) do
        for _, row in pairs(log_configList) do
            print(row.str .. dict[row.name])
        end
    end
end

run_config_log()
