---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 3/12/24 10:55 AM
---

utils = {}

function utils.splitString(inputString)
    local result = {}
    for line in inputString:gmatch("[^\n]+") do
        table.insert(result, line)
    end
    return result
end

function utils.convertSeconds(seconds)
    local date = {}
    date.days = math.floor(seconds / 86400)
    seconds = seconds % 86400
    date.hours = math.floor(seconds / 3600)
    seconds = seconds % 3600
    date.minutes = math.floor(seconds / 60)
    date.sec = seconds % 60
    return date
end

function utils.countDots(str)
    local count = 0
    for char in str:gmatch(".") do
        if char == '.' then
            count = count + 1
        end
    end
    return count
end

function utils.separateLettersAndNumbers(inputString)
    local letters = ""
    local numbers = ""
    for i = 1, #inputString do
        local char = inputString:sub(i, i)
        if tonumber(char) ~= nil then
            numbers = numbers .. char
        else
            letters = letters .. char
        end
    end
    return letters, tonumber(numbers)
end

return utils
