---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 3/12/24 12:16 PM
---
local tf = require "tf_module"

local tf_poe_module = {}

local cmd_show_poe_config   = "ubus call uci get '{\"config\":\"poe\"}'"
local cmd_show_port_config  = "ubus call uci get '{\"config\":\"port\"}'"
local cmd_show_poe_status   = "ubus call poe info"

tf_poe_module.portsEnum = {
    port        = "Port: ",
    poe_plus    = "\tpoe plus:  ",
    priority    = "\tpriority:  ",
    status      = "\tstatus:     \t",
    consumption = "\tconsumption:\t",
}

tf_poe_module.statusEnum = {
    ["Searching"] = 2,
    ["Delivering power"] = 1
}

tf_poe_module.poe_enum = {
    firmware    = "firmware",
    mcu         = "\tMcu:         ",
    budget      = "\tBudget:      ",
    consumption = "\tConsumption: ",
    ports       = "ports"
}

tf_poe_module.portPoE_config =
{
    portPoeState = { "poe", "PoE State: " }
}

function tf_poe_module.getPoeStatusInfo()
    local jsonPoeInfo = tf.collectJsonTable(cmd_show_poe_status)
    return jsonPoeInfo
end

function tf_poe_module.getPoeConfig()
    local poeConfigInfo = tf.collectJsonTable(cmd_show_poe_config)
    return poeConfigInfo.values
end

function tf_poe_module.getPoeStateInfo(portNum)
    local resPoeState = {}
    local cmd = ""
    if portNum == "all" then
        cmd = cmd_show_port_config
    else
        cmd = cmd_show_port_config .. ",\"section\":\"" .. portNum .. "\"}'"
    end
    --print("cmd = " .. cmd)
    resPoeState = tf.collectJsonTable(cmd)
    return resPoeState
end

return tf_poe_module




