#!/usr/bin/lua

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 7/26/24 12:49 PM
---
local tf = require "tf_module"
local i2c = require "i2c_module"

local ubus_cmd_prefix = "ubus call hw_sensor getStatus '{\"category\":\"sfp"
local ubus_cd_suffix = "\"}'"

local function run_show_sfp()
    local ubus_cmd = ubus_cmd_prefix .. arg[1] .. ubus_cd_suffix
    local sfp_jsonInfo = tf.collectJsonTable(ubus_cmd)
    if sfp_jsonInfo.hw_sys ~= nil then
        sfp_jsonInfo = sfp_jsonInfo.hw_sys
        local sfplist = i2c.sfpList
        for _, dict in pairs(sfplist) do
            local name = dict.name .. "_" .. arg[1]
            print(dict.str .. sfp_jsonInfo[name])
        end
    end
end

run_show_sfp()



