#!/usr/bin/lua

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 7/24/24 3:42 PM

local tf = require "tf_module"
local i2c = require "i2c_module"

local ubus_cmd = "ubus call hw_sensor getStatus '{\"category\":\"ups\"}'"

local function run_main_ups()
    local json_UpsInfo = tf.collectJsonTable(ubus_cmd)

    json_UpsInfo = json_UpsInfo.hw_sys
    for i, dict in pairs(i2c.ups_list) do
        if dict.enumValue == nil then
            print(dict.str .. json_UpsInfo[dict.name])
        elseif dict.enumValue ~= nil then
            local index = tonumber(json_UpsInfo[dict.name]) + 1
            print(dict.str .. dict.enumValue[index])
        end
    end
end

run_main_ups()

