#!/bin/sh /etc/rc.common

START=97
STOP=01
USE_PROCD=1
PROG=/usr/bin/tf_autorestartd

#with executable
start_instance() {
  echo "start_instance"
  local cfg="$1"
  local enabled

  config_get_bool enabled "$cfg" 'enabled' 0

  #[ $enabled -gt 0 ] || return 1

  procd_open_instance
  procd_set_param command $PROG
  # Send stdout/stderr output to the system log
  # Use command logread to see the log
  procd_set_param stderr 1
  procd_set_param stdout 1
  procd_close_instance
}

stop_instance() {
  local cfg="$1"
}

reload_service()
{
  stop
  start
}

start_service() {
  config_load 'tf_autorestart'
  config_foreach start_instance 'tf_autorestart'
}

stop_service() {
  config_load 'tf_autorestart'
  config_foreach stop_instance 'tf_autorestart'
}

service_triggers()
{
    procd_add_reload_trigger tf_autorestart
}


