---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 6/4/24 9:44 AM
---

local stp_module = {}

stp_module.cmdList = {
    get_mstpdConfig = "ubus call uci get \'{\"config\":\"mstpd\"}\'",
    get_netConfig   = "ubus call uci get \'{\"config\":\"network\"}\'",
    stp_status      = "ubus call mstpd getStatus \'{\"bridge\":\"switch\"}\'"
}

stp_module.cmd_paramList =
{
    state           = "state",
    loglevel        = "loglevel",
    priority        = "priority",
    protocol        = "protocol",
    ageing          = "ageing",
    hellotime       = "hellotime",
    forwarddelay    = "forwarddelay",
    maxage          = "maxage",
    txholdcount     = "txholdcount",
}

stp_module.mstpdParam = {
    bridges = {
        {"bridge",                      "\tBridge name:                " },      --  1
        {"enabled",                     "\tBridge enabled:             " },      --  2
        {"bridge-id",                   "\tBridge ID:                  " },      --  3
        {"root-port",                   "\tRoot port:                  " },      --  4
        {"designated-root",             "\tDesignated root:            " },      --  5
        {"regional-root",               "\tRegional root:              " },      --  6
        {"topology-change-port",        "\tTopology change port:       " },      --  7
        {"last-topology-change-port",   "\tLast topology change port:  " },      --  8
        {"topology-change",             "\tTopology change:            " },      --  9
        {"topology-change-count",       "\tTopology change count:      " },      --  10
        {"time-since-topology-change",  "\tTime since topology change: " },      --  11
        {"bridge-max-age",              "\tBridge max age:             " },      --  12
        {"hello-time",                  "\tHello time:                 " },      --  13
        {"tx-hold-count",               "\tTX hold count:              " },      --  14
        {"path-cost",                   "\tPath cost:                  " },      --  15
        {"internal-path-cost",          "\tInternal path cost:         " },      --  16
        {"max-hops",                    "\tMax hops:                   " },      --  17
        {"max-age",                     "\tMax age:                    " },      --  20
        {"ageing-time",                 "\tAgeing time:                " },      --  18
        {"forward-delay",               "\tForward delay:              " },      --  19
        {"bridge-forward-delay",        "\tBridge forward delay:       " },      --  21
        {"force-protocol-version",      "\tForce protocol version:     " },      --  22
        {"ports",                       "Ports:                        " }       --  23
    },

    br_port =
    {
        {"port",                    "Port:  "                  },                     --  1
        {"role",                    "\tRole:                 " },    --  2
        {"state",                   "\tState:                " },    --  3
        {"bridge",                  "\tBridge:               " },    --  4
        {"port-id",                 "\tID:                   " },    --  5
        {"designated-bridge",       "\tDesignated bridge:    " },    --  6
        {"network-port",            "\tNetwork port:         " },    --  7
        {"enabled",                 "\tPort enabled:         " },    --  8
        {"designated-port",         "\tDesignated-port:      " },    --  9
        {"designated-root",         "\tDesignated root:      " },    --  10
        {"port-hello-time",         "\tHello time:           " },    --  11
        {"bpdu-filter-port",        "\tBPDU filter port:     " },    --  12
        {"bpdu-guard-port",         "\tBPDU guard port:      " },    --  13
        {"bpdu-guard-error",        "\tBPDU guard error:     " },    --  14
        {"received-bpdu",           "\tReceived BPDU:        " },    --  15
        {"received-tcn",            "\tReceived TCN:         " },    --  16
        {"num-rx-bpdu",             "\tNum RX BPDU:          " },    --  17
        {"num-rx-tcn",              "\tNum RX TCN:           " },    --  20
        {"num-rx-bpdu-filtered",    "\tNum RX BPDU filtered: " },    --  18
        {"num-tx-bpdu",             "\tNum TX BPDU:          " },    --  19
        {"send-rstp",               "\tSend RSTP:            " },    --  21
        {"received-rstp",           "\tReceived RSTP:        " },    --  22
        {"received-stp",            "\tReceived STP:         " },    --  23
        {"dsgn-regional-root",      "\tDSGN regional root:   " },    --  24
        {"dsgn-external-cost",      "\tDSGN external cost:   " },    --  25
        {"dsgn-internal-cost",      "\tDSGN internal cost:   " },    --  26
        {"admin-edge-port",         "\tAdmin edge port:      " },    --  27
        {"admin-internal-cost",     "\tAdmin internal cost:  " },    --  28
        {"admin-external-cost",     "\tAdmin external cost:  " },    --  29
        {"point-to-point",          "\tPoint to point:       " },    --  30
        {"restricted-TCN",          "\tRestricted TCN;       " },    --  31
        {"ba-inconsistent",         "\tBA inconsistent:      " },    --  32
        {"oper-edge-port",          "\tOper edge port:       " },    --  33
        {"topology-change-ack",     "\tTopology change ack:  " },    --  34
        {"external-port-cost",      "\tExternal port cost;   " },    --  35
        {"internal-port-cost",      "\tInternal port cost:   " },    --  36
        {"num-transition-fwd",      "\tNum transition fwd:   " },    --  37
        {"received-tc-ack",         "\tReceived tc ack:      " },    --  38
        {"admin-point-to-point",    "\tAdmin point to point: " },    --  39
        {"disputed",                "\tDisputed:             " },    --  40
        {"num-transition-blk",      "\tNum transition blk:   " },    --  41
        {"num-tx-tcn",              "\tNum TX TCN:           " },    --  42
        {"auto-edge-port",          "\tAuto edge port:       " },    --  43
        {"restricted-role",         "\tRestricted role:      " },    --  44
    }
}

return stp_module

